### ISSUE TITLE
Doesn't work After "Selection to Subflow"

### ISSUE THREAD

**Issue by swsmile** [namgk/dnr-editor#13]
### What are the steps to reproduce?
![image](https://user-images.githubusercontent.com/15687188/43686636-2ac613b2-98c1-11e8-9db8-9636aea70c38.png)

![image](https://user-images.githubusercontent.com/15687188/43686638-2e37a25e-98c1-11e8-8c80-a074b9fbca3b.png)

##### Before "Selection to Subflow"
![image](https://user-images.githubusercontent.com/15687188/43686644-42e1f9de-98c1-11e8-991d-46e3a4a60141.png)

Here is the corresponding JSON of this flow:
```json
[{"id":"ee6711f4.ef043","type":"http in","z":"1b53be18.b0a122","name":"","url":"/test0","method":"get","upload":false,"swaggerDoc":"","x":120,"y":160,"wires":[["2671010.e829e"]],"constraints":{}},{"id":"e680303d.fb92b","type":"http response","z":"1b53be18.b0a122","name":"","statusCode":"","headers":{},"x":470,"y":160,"wires":[],"constraints":{}},{"id":"2671010.e829e","type":"function","z":"1b53be18.b0a122","name":"LogOnly2","func":"msg.payload = {\"a\":\"b\"};\nconsole.log(\"log2\");\nreturn msg;","outputs":1,"noerr":0,"x":300,"y":160,"wires":[["e680303d.fb92b"]],"constraints":{}}]
```

##### After "Selection to Subflow"

![image](https://user-images.githubusercontent.com/15687188/43687465-6b7640ec-98cd-11e8-89a8-f7db23537cca.png)

![image](https://user-images.githubusercontent.com/15687188/43687415-a2a0e104-98cc-11e8-87fd-3446ab3da125.png)

![image](https://user-images.githubusercontent.com/15687188/43687418-b24e8cfa-98cc-11e8-92a3-1de27bc101cb.png)

Here is the corresponding JSON of this flow:
```json
[{"id":"19b6afe.fea9d5","type":"subflow","name":"Subflow 7","info":"","in":[{"x":160,"y":160,"wires":[{"id":"2671010.e829e"}]}],"out":[{"x":440,"y":160,"wires":[{"id":"2671010.e829e","port":0}]}]},{"id":"2671010.e829e","type":"function","z":"19b6afe.fea9d5","name":"LogOnly2","func":"msg.payload = {\"a\":\"b\"};\nconsole.log(\"log2\");\nreturn msg;","outputs":1,"noerr":0,"x":300,"y":160,"wires":[[]],"constraints":{}},{"id":"ee6711f4.ef043","type":"http in","z":"1b53be18.b0a122","name":"","url":"/test0","method":"get","upload":false,"swaggerDoc":"","x":120,"y":160,"wires":[["5de036f6.b93638"]],"constraints":{}},{"id":"e680303d.fb92b","type":"http response","z":"1b53be18.b0a122","name":"","statusCode":"","headers":{},"x":470,"y":160,"wires":[],"constraints":{}},{"id":"5de036f6.b93638","type":"subflow:19b6afe.fea9d5","z":"1b53be18.b0a122","x":300,"y":160,"wires":[["e680303d.fb92b"]]}]
```
### What happens?
 Before "Selection to Subflow", I can visit http://localhost:12002/test0 on browser (without any error on terminal also).
![image](https://user-images.githubusercontent.com/15687188/43686686-dfc80b4e-98c1-11e8-8f86-d02b623294fd.png)

 After "Selection to Subflow" and I visit http://localhost:12002/test0 again on browser, it shows a error `TypeError: Cannot read property 'configs' of undefined` on Node-RED instance 1 (run on port 12001).
![image](https://user-images.githubusercontent.com/15687188/43687477-ae950a5c-98cd-11e8-97e1-c67baed71426.png)

```
TypeError: Cannot read property 'configs' of undefined
    at createSubflow (/Users/weishi/Desktop/OneDrive/Dissertation/Project/NodeRed-subnode2/node-red/red/runtime/nodes/flows/Flow.js:341:18)
    at Flow.start (/Users/weishi/Desktop/OneDrive/Dissertation/Project/NodeRed-subnode2/node-red/red/runtime/nodes/flows/Flow.js:97:41)
    at start (/Users/weishi/Desktop/OneDrive/Dissertation/Project/NodeRed-subnode2/node-red/red/runtime/nodes/flows/index.js:327:29)
    at /Users/weishi/Desktop/OneDrive/Dissertation/Project/NodeRed-subnode2/node-red/red/runtime/nodes/flows/index.js:164:21
    at tryCatchReject (/Users/weishi/Desktop/OneDrive/Dissertation/Project/NodeRed-subnode2/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/weishi/Desktop/OneDrive/Dissertation/Project/NodeRed-subnode2/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/weishi/Desktop/OneDrive/Dissertation/Project/NodeRed-subnode2/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/Users/weishi/Desktop/OneDrive/Dissertation/Project/NodeRed-subnode2/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/weishi/Desktop/OneDrive/Dissertation/Project/NodeRed-subnode2/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/weishi/Desktop/OneDrive/Dissertation/Project/NodeRed-subnode2/node-red/node_modules/when/lib/Scheduler.js:27:9)
```

### What do you expect to happen?
Can visit http://localhost:12002/test0 correctly.

It seems that the reason of that is there is no definition of the "Subflow 7" in Node-RED instance 1 (run on port 12001).

![image](https://user-images.githubusercontent.com/15687188/43687515-41042328-98ce-11e8-8c75-117cb6cd2ef9.png)

### Please tell us about your environment:

- [ ] Node-RED version:0.18.7
- [ ] node.js version:v8.11.2
- [ ] npm version:6.1.0
- [ ] Platform/OS:macOS 10.13.6 (17G65)
- [ ] Browser:Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by namgk** [comment]
Hi,

Subflow is not implemented yet so that's why the error. 

For the work around, please use the full flow in the design. A little bit inconvenience I agree :(

Thanks

**Comment by swsmile** [comment]
Hi,

Thanks for your reply.

Using a full flow will be OK.
