### ISSUE TITLE
Output links breaks after dnr-editor deploy to node-red

### ISSUE THREAD

**Issue by rpuglielli** [namgk/dnr-editor#14]
### What are the steps to reproduce?
Create an output link to others flows
Input links works perfectly.

### What happens?
When I deploy my dnr-editor flow with a output link to others flows, all the flows crash.

Before deploy in dnr-editor:
![screen shot 2018-08-23 at 11 22 18](https://user-images.githubusercontent.com/17271559/44531499-4fa95400-a6c7-11e8-8185-ddc1a6a5e623.png)
![screen shot 2018-08-23 at 11 23 08](https://user-images.githubusercontent.com/17271559/44531511-56d06200-a6c7-11e8-82cc-7ff58e1feb0e.png)

After deploy in node-red
![screen shot 2018-08-23 at 11 23 48](https://user-images.githubusercontent.com/17271559/44531521-5b951600-a6c7-11e8-9fbb-76bad399fd90.png)
![screen shot 2018-08-23 at 11 24 02](https://user-images.githubusercontent.com/17271559/44531526-5e900680-a6c7-11e8-93e4-c01ee4c24725.png)

### What do you expect to happen?
I notice that when I do a deploy, the name of the flows in the output links are not being updated to the name of the flows in the node-red cluster. 
The input links do this updated by default

### Please tell us about your environment:
I have one instance containing dnr-editor and two instances with node-red integrated to dnr-editor.

- [ ] Node-RED version: Latest
- [ ] node.js version: v8.11.3
- [ ] npm version: 6.3.0
- [ ] Platform/OS: Debian GNU/Linux 9 (stretch)
- [ ] Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by namgk** [comment]
close due to link nodes not supported/tested.
