### ISSUE TITLE
dnr installation issue

### ISSUE THREAD

**Issue by viixiv** [namgk/dnr-editor#16]
Hello Namgk

Thank you for creating this amazing tool. I am completely new to nodejs and node-red so please allow me to ask a very rookie question. I am currently attempting to install the dnr-editor via both npm and git clone as instructed. However I am running into a series of warnings including many deprecated packages. I have attempted to install some of them individually however the problem still persist. Could you please help me take a look at the log and perhaps point out what I might have done wrong. Thanks in advance for your time and attention! 
[npm dnr editor install output.txt](https://github.com/namgk/dnr-editor/files/2831180/npm.dnr.editor.install.output.txt)

**Comment by namgk** [comment]
Hi,

Does it run ok?

Deprecation warnings are prevalent nowadays, the project depends on many other libraries and they also depend on a lot more others. 

Each of them need maintenance effort to keep up with one another, which is sometimes difficult.

**Comment by viixiv** [comment]
Hi,
Thank you for elaborating. Unfortunately I do not think the node is working because I can not see Node Requirement tab in GUI

**Comment by namgk** [comment]
If you install from github, you might need to do a grunt build to build the
assets.

And double check the port, 1818 not 1880.

 What version of dnr-editor are you having?

If nothing works, can you send the log of dnr running?

Thanks

**Comment by viixiv** [comment]
Hi. Thank you for the advice 

The DNR editor is @0.19.4-4.1.0. Just in case I have attached the complete list of npm packages. 

```
C:\Users\XXXX\AppData\Roaming\npm
+-- azure-cli@0.10.20
+-- bcrypt@3.0.3
+-- dnr-editor@0.19.4-4.1.0
+-- grunt-cli@1.3.2
+-- karma-cli@2.0.0
+-- node-inspector@1.1.2
+-- node-red@0.19.5
+-- node-red-contrib-emotiv-bci@1.5.1-3
+-- node-red-contrib-python3-function@0.0.4
+-- nodemon@1.18.9
+-- phantomjs@2.1.7
+-- ttf2woff2@2.0.3
`-- windows-build-tools@5.1.0
```

Port 1818 can not be reached when node-red is running. I checked the available port list with `netstat -ano` and no such port can be found.

I am sorry for my unfamiliarity with github and npm. I do not know how to initiate grunt install and export log file of a specific package operation. Could you kindly provide some instructions or references?

Thanks for your time and patience

**Comment by namgk** [comment]
Could you please try this:

* clone this repo and go to its folder
* run "npm install" or "yarn" (if you don't have yarn, install it first also) -> this step should be success
* run "npm run build", or "yarn build" --> this step should also be success
* edit the settings.js file, change the uiPort to 1818 and comment out the userDir setting
* run "node red"
* go to http://localhost:1818

Let me know your problem on each of these steps.

Thanks

**Comment by namgk** [comment]
close for inactivity, there's now a docker container ready to run if you want to try it out.

Thanks
