### ISSUE TITLE
dnr-editor home page is empty

### ISSUE THREAD

**Issue by SrinivasAiyar** [namgk/dnr-editor#5]
1. Installed dnr-editor using "npm install dnr-ediitor"
2. Using Windows 7 and the Chrome browser Version 61.0.3163.100 (Official Build) (64-bit).  
3. Brought up http://127.0.0.1:1818

Result:
![image](https://user-images.githubusercontent.com/9661827/31405146-07a14d9c-adb3-11e7-9be1-971000a22f58.png)

![image](https://user-images.githubusercontent.com/9661827/31405192-2debc004-adb3-11e7-8604-818d3dc44285.png)
![image](https://user-images.githubusercontent.com/9661827/31405219-42933960-adb3-11e7-9d05-2bad9cc45476.png)

The browser console complains of type error.  Seems to have to do with Google api ...
[127.0.0.1-1507661137633.txt](https://github.com/namgk/dnr-editor/files/1373076/127.0.0.1-1507661137633.txt)
[127.0.0.1-1507661232563.txt](https://github.com/namgk/dnr-editor/files/1373077/127.0.0.1-1507661232563.txt)
[CantReadProperty.js.txt](https://github.com/namgk/dnr-editor/files/1373079/CantReadProperty.js.txt)

**Comment by namgk** [comment]
Hi there,

I'm looking at the binary distribution to see what's the problem. For the moment, you can have it run by doing a source install instead:

> git clone git@github.com:namgk/dnr-editor.git
> cd dnr-editor
> npm install
> ./node_modules/.bin/grunt build
> node red

Thanks

**Comment by namgk** [comment]
I've just published new version on npm. Can you try again with "npm install -g dnr-editor"?

Thanks

**Comment by SrinivasAiyar** [comment]
This is much better!  

The issue now is that the flow gets updated on the registered node-red devices but doesn't run reliably.  It executes a couple of times with a and then stops.
Also the global flow received by registered device has no configs property resulting in access violation, which I hacked around.

**Comment by namgk** [comment]
can you open another issue with respective problem? I need to be able to reproduce your error.

Thanks, I'm closing this.
