### ISSUE TITLE
Seed flow are not deployed successfully to node-red

### ISSUE THREAD

**Issue by AleksandrBezrukov** [namgk/dnr-editor#8]
I have got error in front-end when trying import dnr-daemon node to node-red:
"TypeError: Cannot read property 'deviceId' of null"

Text from node-red console:
[error] [dnr-daemon:1888cbc9.fb96b4] TypeError: Cannot read property 'deviceId' of null

Exported data from dnr-editor:
 [{"id":"af25fe8d.debf5","type":"tab","label":"DNR Seed"},{"id":"f14195aa.25e298","operatorUrl":"http://127.0.0.1:1818","type":"dnr-daemon","x":100,"y":100,"z":"af25fe8d.debf5"}]

dnr-editor version: v 0.17.3-1.0.2
Node-RED version: v0.18.2
node-red-contrib-dnr 3.5.16

**Comment by namgk** [comment]
Hi, thanks for trying out. Which node version you are running?

Sorry for the delay.

**Comment by AleksandrBezrukov** [comment]
Hi. I have Node.js   v6.12.3 and v8.9.4. 
And I have tried node-red-contrib-dnr 2.3.6, 2.3.8, 3.5.16 with Node-RED version: v0.18.2
dnr-editor version: v 0.17.3-1.0.2 and v0.16.9
Same error everywhere. What versions of software should I use? And what versions of software are You using?

**Comment by namgk** [comment]
Hi there,

I think a new dnr-editor version has not been published to npm. Sorry for that. You can install again, it will pull the latest one which is 0.17.3-1.0.3.

**Comment by AleksandrBezrukov** [comment]
Hi namgk.
Error is not fixed.
Log from dnr-editor:
root@nodered-System-Product-Name:/usr/lib/node_modules/dnr-editor# node red
22 Feb 17:28:53 - [info]

Welcome to Node-RED
===================

22 Feb 17:28:53 - [info] Node-RED version: v0.17.3-1.0.3
22 Feb 17:28:53 - [info] Node.js  version: v6.13.0
22 Feb 17:28:53 - [info] Linux 4.13.0-32-generic x64 LE
22 Feb 17:28:53 - [info] Loading palette nodes
22 Feb 17:28:53 - [info] Settings file  : /home/nodered/.node-red/settings.js
22 Feb 17:28:53 - [info] User directory : /Users/nhong/.dnr-editor
22 Feb 17:28:53 - [info] Flows file     : /Users/nhong/.dnr-editor/flows_nodered-System-Product-Name.json
22 Feb 17:28:53 - [info] Creating new flow file
22 Feb 17:28:53 - [info] Starting flows
22 Feb 17:28:53 - [info] Started flows
22 Feb 17:28:53 - [info] Server now running at http://127.0.0.1:1818/

Log from node-red:
root@nodered-VirtualBox:~# node-red
22 Feb 17:23:51 - [info]

Welcome to Node-RED
===================

22 Feb 17:23:51 - [info] Node-RED version: v0.18.3
22 Feb 17:23:51 - [info] Node.js  version: v6.11.4
22 Feb 17:23:51 - [info] Linux 4.13.0-16-generic x64 LE
22 Feb 17:23:52 - [info] Loading palette nodes
22 Feb 17:23:53 - [warn] ------------------------------------------------------
22 Feb 17:23:53 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
22 Feb 17:23:53 - [warn] ------------------------------------------------------
22 Feb 17:23:53 - [info] Settings file  : /home/nodered/.node-red/settings.js
22 Feb 17:23:53 - [info] User directory : /home/nodered/.node-red
22 Feb 17:23:53 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
22 Feb 17:23:53 - [info] Flows file     : /home/nodered/.node-red/flows_nodered-VirtualBox.json
22 Feb 17:23:53 - [info] Creating new flow file
22 Feb 17:23:53 - [info] Server now running at http://127.0.0.1:1880/
22 Feb 17:23:53 - [info] Starting flows
22 Feb 17:23:53 - [info] Started flows

22 Feb 17:25:26 - [info] Installing module: node-red-contrib-dnr, version: 3.5.16
22 Feb 17:25:51 - [info] Installed module: node-red-contrib-dnr
22 Feb 17:25:51 - [info] Added node types:
22 Feb 17:25:51 - [info]  - node-red-contrib-dnr:dnr
22 Feb 17:25:51 - [info]  - node-red-contrib-dnr:dnr-gateway
22 Feb 17:25:51 - [info]  - node-red-contrib-dnr:dnr-placeholder
22 Feb 17:25:51 - [info]  - node-red-contrib-dnr:dnr-daemon
22 Feb 17:25:51 - [info]  - node-red-contrib-dnr:nodered-credentials
22 Feb 17:25:51 - [info]  - node-red-contrib-dnr:operator-credentials
22 Feb 17:29:24 - [info] Stopping flows
22 Feb 17:29:24 - [info] Stopped flows
22 Feb 17:29:24 - [info] Starting flows
22 Feb 17:29:24 - [error] [dnr-daemon:47857765.b94a58] TypeError: Cannot read property 'deviceId' of null
22 Feb 17:29:24 - [info] Started flows

Exported/imported data:

[{"id":"af25fe8d.debf5","type":"tab","label":"DNR Seed"},{"id":"f14195aa.25e298","operatorUrl":"http://10.1.207.220:1818","type":"dnr-daemon","x":100,"y":100,"z":"af25fe8d.debf5"}]

**Comment by namgk** [comment]
Hi Aleksandr,

MY guess is that the dnr seed node hasn’t been configured properly.

In your node red editor (e.g http://localhost:1880) do you see the seed
node deployed there? Do you see any small red triangle next to the node
indicating a bad node configuration?

If yes, double click on it to go to the configuration and configure it.

Thanks

**Comment by AleksandrBezrukov** [comment]
Hi Nam. Thank You. Works fine.
